import type { StreetSegmentCollection } from "@/types/geo";

export const CAMBRIDGE_SEGMENTS: StreetSegmentCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1037, 42.3655],
          [-71.1018, 42.3659],
          [-71.0997, 42.3663],
        ],
      },
      properties: {
        id: "mass-ave-central-1",
        regionId: "cambridge-ma",
        osmWayId: 1001001,
        name: "Massachusetts Ave",
        highwayType: "primary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 350,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.0997, 42.3663],
          [-71.0969, 42.3668],
          [-71.0945, 42.3672],
        ],
      },
      properties: {
        id: "mass-ave-mit-1",
        regionId: "cambridge-ma",
        osmWayId: 1001002,
        name: "Massachusetts Ave",
        highwayType: "primary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 430,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1033, 42.3732],
          [-71.1014, 42.3722],
          [-71.0996, 42.3714],
        ],
      },
      properties: {
        id: "mass-ave-harvard-1",
        regionId: "cambridge-ma",
        osmWayId: 1001003,
        name: "Massachusetts Ave",
        highwayType: "primary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 430,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1004, 42.3737],
          [-71.1002, 42.3713],
          [-71.1001, 42.3691],
        ],
      },
      properties: {
        id: "prospect-st-1",
        regionId: "cambridge-ma",
        osmWayId: 1001004,
        name: "Prospect Street",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 520,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.0949, 42.3735],
          [-71.0969, 42.3715],
          [-71.0991, 42.3696],
        ],
      },
      properties: {
        id: "broadway-1",
        regionId: "cambridge-ma",
        osmWayId: 1001005,
        name: "Broadway",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 610,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1077, 42.3729],
          [-71.1048, 42.3729],
          [-71.1018, 42.3728],
        ],
      },
      properties: {
        id: "brattle-st-1",
        regionId: "cambridge-ma",
        osmWayId: 1001006,
        name: "Brattle Street",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 500,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1102, 42.3733],
          [-71.1074, 42.3734],
          [-71.1042, 42.3735],
        ],
      },
      properties: {
        id: "mount-auburn-st-1",
        regionId: "cambridge-ma",
        osmWayId: 1001007,
        name: "Mount Auburn Street",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 510,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.0937, 42.3597],
          [-71.0918, 42.3608],
          [-71.0892, 42.3619],
        ],
      },
      properties: {
        id: "memorial-drive-1",
        regionId: "cambridge-ma",
        osmWayId: 1001008,
        name: "Memorial Drive Path",
        highwayType: "path",
        access: "public",
        foot: "designated",
        surface: "paved",
        lengthMeters: 410,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.0976, 42.3621],
          [-71.0957, 42.3612],
          [-71.0935, 42.3602],
        ],
      },
      properties: {
        id: "vassar-st-1",
        regionId: "cambridge-ma",
        osmWayId: 1001009,
        name: "Vassar Street",
        highwayType: "cycleway",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 390,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.0998, 42.3649],
          [-71.0978, 42.3639],
          [-71.0957, 42.3629],
        ],
      },
      properties: {
        id: "main-st-mit-1",
        regionId: "cambridge-ma",
        osmWayId: 1001010,
        name: "Main Street",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 380,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1201, 42.3746],
          [-71.1178, 42.3742],
          [-71.1152, 42.3738],
        ],
      },
      properties: {
        id: "fresh-pond-path-1",
        regionId: "cambridge-ma",
        osmWayId: 1001011,
        name: "Fresh Pond Path",
        highwayType: "path",
        access: "public",
        foot: "designated",
        surface: "gravel",
        lengthMeters: 420,
        isWalkable: true,
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [-71.1152, 42.3738],
          [-71.1122, 42.3734],
          [-71.1093, 42.3731],
        ],
      },
      properties: {
        id: "garden-st-1",
        regionId: "cambridge-ma",
        osmWayId: 1001012,
        name: "Garden Street",
        highwayType: "secondary",
        access: "public",
        foot: "yes",
        surface: "asphalt",
        lengthMeters: 500,
        isWalkable: true,
      },
    },
  ],
};

// Made with Bob
